### ISSUE TITLE
Check on root rights

### ISSUE THREAD

**Issue by sanderjo** [apg-intel/ipv6tools#8]
Running server.py resulted in nothing found in the webinterface.

Ah ... it needs root rights ... just like the README Usage says: ```sudo python server.py```.

Anyway: I would prefer a root effective uid check:
```
import os

if __name__ == '__main__':

    if os.geteuid() != 0:
        exit("You need to have root privileges to run this script.\nPlease try again, this time using 'sudo'. Exiting.")

    socketio.run(app)
```

Result:
```
~/git/ipv6tools$ python server.py 
You need to have root privileges to run this script.
Please try again, this time using 'sudo'. Exiting.
```

Shall I send a PR for this?

**Comment by joshporter1** [comment]
Yes, it requires root. Go ahead and send a PR, as providing a uid check with a proper exit is the preferred behavior. Thanks!
